language: r
cache: packages

dist: trusty
sudo: false

warnings_are_errors: true

env:
 global:
   - CRAN=http://cran.rstudio.com

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - libhdf5-serial-dev libnetcdf-dev netcdf-bin

install: true

before_script:
  - Rscript -e "install.packages('ncdf4')"